### PR TITLE
Fixed #warning preprocessor directive

### PR DESCRIPTION
**Pull request by gshimansky**
Added condition to use of `#warning` preprocessor directive

### CODE REVIEW

**Review by alexbaden — APPROVED** [review]
Looks fine for now. Could we make a macro for generating compiler warnings for future use, so we don't have to #ifdef?

**Comment by gshimansky** [comment]
@alexbaden Is there a header file in HDK that is included in all other places in the code where we could define such macro?

**Comment by alexbaden** [comment]
No, usually we would create a new header file in `Shared` and define the macro there. It can then be included where needed. See, for example, `Shared/checked_alloc.h` (not a macro but a free function that is used in a lot of different places).

**Comment by gshimansky** [comment]
@alexbaden There is [BOOST_PRAGMA_MESSAG](https://www.boost.org/doc/libs/1_81_0/boost/config/pragma_message.hpp). What do you think about using it instead?

**Pull request merged**
