### PR TITLE
Updated conda env for windows development

### PR DESCRIPTION
**Pull request by gshimansky**

### CODE REVIEW

**Review by alexbaden — APPROVED** [review]
Looks good. We should look at merging these changes in w/ the Linux version. I don't know if there's a way to do that inside conda, but we could write a shell script to concat them.

**Comment by gshimansky** [comment]
We could probably have some common environment for both platforms and small additions that exist/required on specific platforms (e.g. folly currently exists only on Linux in conda-forge).

**Comment by gshimansky** [comment]
I suggest that we murge this PR while we think on the best way to synchronize multi-platform conda env. This is the last PR that is holding windows build from running CI.

**Comment by aregm** [comment]
> I suggest that we merge this PR while we think on the best way to synchronize multi-platform conda env. This is the last PR that is holding windows build from running CI.

I think we should merge this ASAP, as this is a separate file and do not interfere with Linux builds.

**Review by aregm — APPROVED** [review]

**Pull request merged**
