### PR TITLE
Fix python version to 3.9

### PR DESCRIPTION
**Pull request by leshikus**
This is a workaround for https://github.com/intel-ai/hdk/issues/332 (it fixes development env; runtime env is still needed)

### CODE REVIEW

**Comment by Garra1980** [comment]
try 
- python 3.9.16
in yml file instead just
- python 3.9

**Comment by alexbaden** [comment]
Shouldn't we use python `3.9.*` or equivalent so we will get security updates, etc without having to manually bump the minor version each time?

**Comment by Garra1980** [comment]
> Shouldn't we use python `3.9.*` or equivalent so we will get security updates, etc without having to manually bump the minor version each time?

yes, I think we should try this

**Comment by kurapov-peter** [comment]
What's the point of setting the version for our dev envs anyway?

**Comment by leshikus** [comment]
fixed to 3.9.*

**Comment by Garra1980** [comment]
> What's the point of setting the version for our dev envs anyway?

to sync with our benchmarking envs at least

**Review by alexbaden — APPROVED** [review]

**Pull request merged**
