### PR TITLE
Add release process skeleton

### PR DESCRIPTION
**Pull request by alexbaden**
@vlad-penkin @Garra1980 anything to add?

### CODE REVIEW

**Comment by Garra1980** [comment]
Some words for conda-forge releases maybe?

**Comment by vlad-penkin** [comment]
I suggest to add two steps

```
5. Create GH release with source code archive
6. Build and publish updated conda-forge packages
```

**Comment by leshikus** [comment]
I cannot see from the document how decision is made when release is created. If I have to do something about the release, I need to get some signal.

> 5. Create GH release with source code archive

Let me note that automatic releases on GitHub do not work with submodules. Also IMHO the conda forge docs try to promote modularity to use a source release of one project (e.g. omniscidb) to build another project (e.g. HDK). We may consider to create omniscidb package on coda-forge to meet these requirements.

**Comment by aregm** [comment]
Hey @leshikus I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/hdk-engineering-62cdeb8331693a0017d16d8a/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Review by Garra1980 — APPROVED** [review]

**Review by leshikus — APPROVED** [review]
LGTM

**Review by vlad-penkin — APPROVED** [review]
LGTM

**Pull request merged**
