### PR TITLE
Enable pull check

### PR DESCRIPTION
**Pull request by leshikus**
Subj

### CODE REVIEW

**Review by kurapov-peter — APPROVED** [review]

**Comment by kurapov-peter** [comment]
Oh wait, it duplicates all the workflows.

**Review by kurapov-peter — CHANGES_REQUESTED** [review]
There's something like https://github.com/marketplace/actions/skip-duplicate-actions for example to prevent the duplication. May be something else even better?

**Comment by leshikus** [comment]
Thanks, will look into it

**Comment by leshikus** [comment]
My previous experience shows that Igor generally does not approve use of third party actions. We may have smaller or different set of tests for pull requests.

**Comment by kurapov-peter** [comment]
There is for example this method: https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/

**Comment by leshikus** [comment]
This is a good text. AFAIU they reworked event object, so implementing this will require an additional investigation

**Pull request closed without merging**
